from django.urls import path
from . import views

urlpatterns = [
    path('addusers/', views.setUsers, name='addusers'),
    path('signIn/', views.signIn, name='signIn'),
    path('home/', views.homePage, name='home'),
    path('set_user_post/', views.set_user_post, name='set_user_post'),
    path('set_group/', views.set_group, name='set_group'),
    path('get_groups/', views.get_groups, name='groups'),
    path('get_friend_list/', views.get_friend_list, name='get_friend_list'),
    path('get_friend_req_list/', views.get_friend_req_list, name='get_friend_req_list'),
    path('get_sent_friend_req_list/', views.get_sent_friend_req_list, name='get_sent_friend_req_list'),
    path('get_chat_friend_list/', views.get_chat_friend_list, name='get_chat_friend_list'),
    path('get_events/', views.get_events, name='get_events'),
    path('set_event/', views.set_event, name='set_event'),
    path('search_users/', views.search_users, name='search_users'),
    path('search_groups/', views.search_groups, name='search_groups'),
    path('get_marketplace/', views.get_marketplace, name='get_marketplace'),
    path('set_marketplace/', views.set_marketplace, name='set_marketplace'),
    path('get_user_profile/', views.get_user_profile, name='get_user_profile'),
    path('get_comment_info/', views.get_comment_info, name='get_comment_info'),
    path('get_reply_info/', views.get_reply_info, name='get_reply_info'),
    path('set_post_comment/', views.set_post_comment, name='set_post_comment'),
    path('set_comment_reply/', views.set_comment_reply, name='set_comment_reply'),
    path('update_user_post/', views.update_user_post, name='update_user_post'),
    path('delete_user_post/', views.delete_user_post, name='delete_user_post'),
    path('get_messages/', views.get_messages, name='get_messages'),
    path('set_message/', views.set_message, name='set_message'),
    path('get_group_page/', views.get_group_page, name='get_group_page'),
    path('set_group_post/', views.set_group_post, name='set_group_post'),
    path('is_friend/', views.is_friend, name='is_friend'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('unfriend/', views.unfriend, name='unfriend'),
    path('delete_request/', views.delete_request, name='delete_request'),
    path('send_request/', views.send_request, name='send_request'),
    path('accept_request/', views.accept_request, name='accept_request'),
    path('is_in_group/', views.is_in_group, name='is_in_group'),
    path('delete_group/', views.delete_group, name='delete_group'),
    path('group_reqs/', views.group_reqs, name='group_reqs'),
    path('send_req_in_group/', views.send_req_in_group, name='send_req_in_group'),
    path('accept_req_in_group/', views.accept_req_in_group, name='accept_req_in_group'),
    path('reject_req_in_group/', views.reject_req_in_group, name='reject_req_in_group'),
    path('leave_from_group/', views.leave_from_group, name='leave_from_group'),
]
